fixes likelihood term to make it differentiable at very low temperature. When temp is very low, Botlzmann policy (prob) for lower valued state is 0 which results in torch.tensor(eps) being included in the loss term, but eps was non-differentiable, so it results in following error when loss.backward() is called. ``` 249     # some Python versions print out the first line of a multi-line function     250     # calls in the traceback and some print out the last line --> 251     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass     252         tensors,     253         grad_tensors_,
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```